package ui;

import preprocessing.*;
import classifiers.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
/**
 *
 * @author Hp
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    RandomForest rf;
    ArrayList<ArrayList<String>> trainingData;
    List<String> testRecords;
    Long outputTime;
    public Dashboard() {
        initComponents();
        Border border = BorderFactory.createLineBorder(Color.BLACK, 1);
        imageContainer.setBorder(border);
        PrepareDataset pd = new PrepareDataset();
        trainingData = pd.getData(Initialization.trainDataPath);
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cellTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        browseImageRF = new javax.swing.JButton();
        performRFClassification = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numTrees = new javax.swing.JSpinner();
        numAttributes = new javax.swing.JSpinner();
        trainRFClassifier = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        rfImagePath = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numNeighbours = new javax.swing.JSpinner();
        jSeparator3 = new javax.swing.JSeparator();
        browseImageKnn = new javax.swing.JButton();
        knnImagePath = new javax.swing.JTextField();
        performKnnClassification = new javax.swing.JButton();
        setNeightbours = new javax.swing.JButton();
        imageContainer = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newFeatureFile = new javax.swing.JMenuItem();
        performAnalysis = new javax.swing.JMenuItem();
        settings = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitSystem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cellTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cell (Binary)", "Cell (Grayscale)", "Condition"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cellTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cellTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(cellTable);
        if (cellTable.getColumnModel().getColumnCount() > 0) {
            cellTable.getColumnModel().getColumn(0).setResizable(false);
            cellTable.getColumnModel().getColumn(1).setResizable(false);
            cellTable.getColumnModel().getColumn(2).setResizable(false);
        }

        browseImageRF.setText("Browse Image");
        browseImageRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseImageRFActionPerformed(evt);
            }
        });

        performRFClassification.setText("Classify");
        performRFClassification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performRFClassificationActionPerformed(evt);
            }
        });

        jLabel1.setText("Number of Trees");

        jLabel2.setText("Number of Attributes");

        numTrees.setModel(new javax.swing.SpinnerNumberModel(151, 1, 501, 2));
        numTrees.setVerifyInputWhenFocusTarget(false);

        numAttributes.setModel(new javax.swing.SpinnerNumberModel(4, 1, 7, 1));

        trainRFClassifier.setText("Train Classifier");
        trainRFClassifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainRFClassifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numTrees, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(numAttributes))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(browseImageRF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rfImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addComponent(trainRFClassifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(performRFClassification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numTrees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trainRFClassifier)
                .addGap(9, 9, 9)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rfImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseImageRF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(performRFClassification)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Random Forest", jPanel1);

        jLabel3.setText("Number of Neighbours");

        numNeighbours.setModel(new javax.swing.SpinnerNumberModel(3, 1, 15, 2));

        browseImageKnn.setText("Browse Image");
        browseImageKnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseImageKnnActionPerformed(evt);
            }
        });

        performKnnClassification.setText("Classify");
        performKnnClassification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performKnnClassificationActionPerformed(evt);
            }
        });

        setNeightbours.setText("Set");
        setNeightbours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNeightboursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(performKnnClassification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(browseImageKnn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(knnImagePath))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numNeighbours, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 198, Short.MAX_VALUE))
                    .addComponent(setNeightbours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numNeighbours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(setNeightbours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseImageKnn)
                    .addComponent(knnImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(performKnnClassification)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("kNN", jPanel2);

        imageContainer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageContainer.setText("Image Not Loaded");

        jMenu1.setText("File");

        newFeatureFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newFeatureFile.setText("New Feature File");
        newFeatureFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFeatureFileActionPerformed(evt);
            }
        });
        jMenu1.add(newFeatureFile);

        performAnalysis.setText("Analysis");
        performAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performAnalysisActionPerformed(evt);
            }
        });
        jMenu1.add(performAnalysis);

        settings.setText("Settings");
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });
        jMenu1.add(settings);
        jMenu1.add(jSeparator1);

        exitSystem.setText("Exit");
        exitSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitSystemActionPerformed(evt);
            }
        });
        jMenu1.add(exitSystem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startTimer() {
        outputTime = System.currentTimeMillis();
    }
    
    private static String timeElapsed(long time) {
        double s = (double) (System.currentTimeMillis() - time) / 1000;
        int h = (int) Math.floor(s / ((double) 3600));
        s -= (h * 3600);
        int m = (int) Math.floor(s / ((double) 60));
        s -= (m * 60);
        return m + " minute(s) " + s + " second(s)";
    }
    
    private void performAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performAnalysisActionPerformed
            AnalysisPanel ap = new AnalysisPanel();
            JOptionPane.showOptionDialog(null, ap,
            "Analysis", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,null,new Object[]{},null);
            
    }//GEN-LAST:event_performAnalysisActionPerformed

    private void performRFClassificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performRFClassificationActionPerformed
            try {
                Initialization.src = ImageIO.read(new File(rfImagePath.getText()));
                DefaultTableModel dtm = (DefaultTableModel) cellTable.getModel();
                dtm.getDataVector().removeAllElements();
                dtm.fireTableDataChanged();
//                while(dtm.getRowCount() > 0)
//                    dtm.removeRow(0);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            ProgressMonitor ceProgressMonitor = new ProgressMonitor(this,"Preprocessing Image","",0,100);
            ceProgressMonitor.setMillisToPopup(500);
            SwingWorker cellExtractor = new SwingWorker<Integer,Integer> ()    {
                @Override
                protected Integer doInBackground() throws Exception {
                    testRecords = new ArrayList<>();
                    Initialization.numAttrs = (Integer) numAttributes.getValue();
                    Initialization.numTrees = (Integer) numTrees.getValue();
                    rf = new RandomForest(Initialization.numTrees,4,7,Initialization.numAttrs,2,trainingData);
                    rf.readFromFile();
                    startTimer();
                    ceProgressMonitor.setNote("Performing Grayscale Conversion");
                    new Grayscale().convert();
                    publish(12);
                    ceProgressMonitor.setNote("Performing Histogram Equalization");
                    new HistogramEqualization().performHistEqualization();
                    publish(25);
                    ceProgressMonitor.setNote("Performing Contrast Stretching");
                    new ContrastStretching().performcs();
                    publish(37);
                    ceProgressMonitor.setNote("Performing Image Arithmetic");
                    new ImageArithmetic().compute();
                    publish(50);
                    ceProgressMonitor.setNote("Performing Median Filtering");
                    new MedianFilter().performmf();
                    publish(63);
                    ceProgressMonitor.setNote("Converting to Binary Image");
                    new KMeans().init();
                    publish(75);
                    ceProgressMonitor.setNote("Performing Opening");
                    new Opening().open();
                    publish(80);
                    ceProgressMonitor.setNote("Extracting Components");
                    Initialization.numComponents = new SAGAP().perform();
                    for(int i=1;i<=Initialization.numComponents;i++)   {
                        FeatureExtraction fe = new FeatureExtraction();
                        fe.computeFeatures("Components\\Component"+i+".png","Components\\GComponent"+i+".png");
                        fe.computePerimeter("Components\\Component"+i+".png");
                        String record = fe.getArea() + ","
                            + fe.getPerimeter() + "," + fe.getFormFactor() + "," + fe.getStd() + "," 
                            + fe.getVar() + "," + fe.getEnergy() + "," + fe.getEntropy() + ","
                            + "test";
                                        
                //String s = "1833.48,439.48737341529164,0.11928703298994943,8.907680240547194,79.34676726783492,0.03126279141729138,5.172957073376205";
                        
                        testRecords.add(rf.classify(new ArrayList<>(Arrays.asList(record.split(",")))));
                    }
                    return 100; 
                }
                
                @Override
                protected void process(List<Integer> chunks)    {
                    int val = chunks.get(chunks.size()-1);
                    ceProgressMonitor.setProgress(val);
                }

                @Override
                protected void done()   {
                    ceProgressMonitor.close();
                    populateTable();
                }
                
            };
            cellExtractor.execute();
    }//GEN-LAST:event_performRFClassificationActionPerformed
    
    private void populateTable()    {
        String [] columns = {"Cell (Binary)", "Cell (Grayscale)", "Condition"};
        Object [][] data   = new Object [Initialization.numComponents][3];
        for(int i=1;i<=Initialization.numComponents;i++) {
            try {
                data[i-1][0] = new ImageIcon(ImageIO.read(new File("Components\\Component" + i + ".png")));
                data[i-1][1] = new ImageIcon(ImageIO.read(new File("Components\\GComponent" + i + ".png")));
                data[i-1][2] = testRecords.get(i-1).equals("true")?"Affected":"Not Affected";   
            } catch (IOException ex) {
                ex.printStackTrace();
            } 
        }
        DefaultTableModel model = new DefaultTableModel(data,columns)
        {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            @Override
            public Class getColumnClass(int column) {
                return getValueAt(0, column).getClass();
            }
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }   
        };
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( SwingConstants.CENTER );
        centerRenderer.setVerticalAlignment( SwingConstants.CENTER );
        cellTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        cellTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        cellTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        cellTable.setShowGrid(true);
        cellTable.setModel(model);
        
        for(int i=1;i<=Initialization.numComponents;i++)  {
            cellTable.setRowHeight(i-1,((Icon) data[i-1][0]).getIconHeight() + 10);
        }
        int numNotAffected = 0;
        int numAffected = 0;
        for(String c : testRecords) {
            if(c.equals("true"))    numAffected++;
            else    numNotAffected++;
        }

        JOptionPane.showMessageDialog(this,"Completed in " + timeElapsed(outputTime) + "\n" + Initialization.numComponents
                + " componented detected.\nAffected Cells : " + numAffected + "\nUnaffected Cells : " + numNotAffected ,
            "Completed", JOptionPane.PLAIN_MESSAGE);
    }
    
    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        SettingsPanel sp = new SettingsPanel();
        SettingsPanel.testPath.setText(Initialization.testDataPath);
        SettingsPanel.trainPath.setText(Initialization.trainDataPath);
        SettingsPanel.rfClassificationFilePath.setText(Initialization.rfClassificationFilePath);
        int result = JOptionPane.showConfirmDialog(null, sp,
            "Settings", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            Initialization.testDataPath = SettingsPanel.testPath.getText();
            Initialization.trainDataPath = SettingsPanel.trainPath.getText();
            Initialization.rfClassificationFilePath = SettingsPanel.rfClassificationFilePath.getText();
            Initialization.update();
        }
    }//GEN-LAST:event_settingsActionPerformed

    private void browseImageRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseImageRFActionPerformed
        JFileChooser fc=new JFileChooser("D:\\Dataset\\ALL_IDB1\\images");
        fc.setDialogTitle("Select an Image");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "png", "gif","jpg","jpeg");
        fc.setFileFilter(filter);
        fc.removeChoosableFileFilter(fc.getAcceptAllFileFilter());
        ImagePreviewPanel preview = new ImagePreviewPanel();
        fc.setAccessory(preview);
        fc.addPropertyChangeListener(preview);
        int i = fc.showOpenDialog(this);
        if(i==JFileChooser.APPROVE_OPTION){
            File f=fc.getSelectedFile();
            String filePath=f.getPath();
            try{
                rfImagePath.setText(filePath);
                Initialization.src = ImageIO.read(new File(filePath));
                ImageIcon im = new ImageIcon(Initialization.src.getScaledInstance(imageContainer.getWidth(), imageContainer.getHeight(),Image.SCALE_SMOOTH));
                imageContainer.setIcon(im);
            }
            catch(Exception e)  {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_browseImageRFActionPerformed

    private void newFeatureFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFeatureFileActionPerformed
        ExtractFeaturesPanel ef = new ExtractFeaturesPanel();
        JOptionPane.showOptionDialog(null, ef,
            "Create Feature File", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,null,new Object[]{},null);
    }//GEN-LAST:event_newFeatureFileActionPerformed

    private void exitSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitSystemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitSystemActionPerformed

    private void trainRFClassifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainRFClassifierActionPerformed
        JDialog rfProgressPanel = new JDialog();
        JProgressBar rfProgress = new JProgressBar();
        rfProgress.setIndeterminate(true);
        rfProgressPanel.setLocationRelativeTo(this);
        rfProgressPanel.setLocation(300,300);
        rfProgressPanel.add(rfProgress);
        rfProgressPanel.setSize(new Dimension(300,50));
        rfProgressPanel.setTitle("Generating Trees");
        rfProgressPanel.setModalityType(Dialog.ModalityType.APPLICATION_MODAL); 
        Initialization.numAttrs = (Integer) numAttributes.getValue();
        Initialization.numTrees = (Integer) numTrees.getValue();
        
        SwingWorker randomForestGenerator = new SwingWorker<Integer,String>   ()   {
            @Override
            protected Integer doInBackground() {
                publish("Started");
                rf = new RandomForest(Initialization.numTrees,4,7,Initialization.numAttrs,2,trainingData);
                rf.writeToFile(); 
//                rf.readFromFile();
//                String s = "1833.48,439.48737341529164,0.11928703298994943,8.907680240547194,79.34676726783492,0.03126279141729138,5.172957073376205";
//                rf.classify(new ArrayList<>(Arrays.asList(s.split(","))));
                return 100;
            }
            
            @Override
            protected void process(List<String> chunks) {
                rfProgressPanel.setVisible(true);
            }
            @Override
            protected void done()   {
                rfProgressPanel.setVisible(false);
            }
        }; 
        randomForestGenerator.execute();
    }//GEN-LAST:event_trainRFClassifierActionPerformed

    private void browseImageKnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseImageKnnActionPerformed
        JFileChooser fc=new JFileChooser("D:\\Dataset\\ALL_IDB1\\images");
        fc.setDialogTitle("Select an Image");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "png", "gif","jpg","jpeg");
        fc.setFileFilter(filter);
        fc.removeChoosableFileFilter(fc.getAcceptAllFileFilter());
        ImagePreviewPanel preview = new ImagePreviewPanel();
        fc.setAccessory(preview);
        fc.addPropertyChangeListener(preview);
        int i = fc.showOpenDialog(this);
        if(i==JFileChooser.APPROVE_OPTION){
            File f=fc.getSelectedFile();
            String filePath=f.getPath();
            try{
                knnImagePath.setText(filePath);
                Initialization.src = ImageIO.read(new File(filePath));
                ImageIcon im = new ImageIcon(Initialization.src.getScaledInstance(imageContainer.getWidth(), imageContainer.getHeight(),Image.SCALE_SMOOTH));
                imageContainer.setIcon(im);
            }
            catch(Exception e)  {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_browseImageKnnActionPerformed

    private void setNeightboursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNeightboursActionPerformed
        Initialization.numNeighbours = (Integer) numNeighbours.getValue();
    }//GEN-LAST:event_setNeightboursActionPerformed

    private void performKnnClassificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performKnnClassificationActionPerformed
        try {
                Initialization.src = ImageIO.read(new File(knnImagePath.getText()));
                DefaultTableModel dtm = (DefaultTableModel) cellTable.getModel();
                dtm.getDataVector().removeAllElements();
                dtm.fireTableDataChanged();
//                while(dtm.getRowCount() > 0)
//                    dtm.removeRow(0);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            ProgressMonitor ceProgressMonitor = new ProgressMonitor(this,"Preprocessing Image","",0,100);
            ceProgressMonitor.setMillisToPopup(500);
            SwingWorker cellExtractor = new SwingWorker<Integer,Integer> ()    {
                @Override
                protected Integer doInBackground() throws Exception {
                    testRecords = new ArrayList<>();
                    startTimer();
                    ceProgressMonitor.setNote("Performing Grayscale Conversion");
                    new Grayscale().convert();
                    publish(12);
                    ceProgressMonitor.setNote("Performing Histogram Equalization");
                    new HistogramEqualization().performHistEqualization();
                    publish(25);
                    ceProgressMonitor.setNote("Performing Contrast Stretching");
                    new ContrastStretching().performcs();
                    publish(37);
                    ceProgressMonitor.setNote("Performing Image Arithmetic");
                    new ImageArithmetic().compute();
                    publish(50);
                    ceProgressMonitor.setNote("Performing Median Filtering");
                    new MedianFilter().performmf();
                    publish(63);
                    ceProgressMonitor.setNote("Converting to Binary Image");
                    new KMeans().init();
                    publish(75);
                    ceProgressMonitor.setNote("Performing Opening");
                    new Opening().open();
                    publish(80);
                    ceProgressMonitor.setNote("Extracting Components");
                    Initialization.numComponents = new SAGAP().perform();
                    for(int i=1;i<=Initialization.numComponents;i++)   {
                        FeatureExtraction fe = new FeatureExtraction();
                        fe.computeFeatures("Components\\Component"+i+".png","Components\\GComponent"+i+".png");
                        fe.computePerimeter("Components\\Component"+i+".png");
                        String record = fe.getArea() + ","
                            + fe.getPerimeter() + "," + fe.getFormFactor() + "," + fe.getStd() + "," 
                            + fe.getVar() + "," + fe.getEnergy() + "," + fe.getEntropy();
                        Initialization.numNeighbours = (Integer) numNeighbours.getValue();;
                        KNN.kValue = Initialization.numNeighbours;
                        testRecords.add(new KNN().perform(record));
                        //testRecords.add();
                    }
                    return 100; 
                }
                
                @Override
                protected void process(List<Integer> chunks)    {
                    int val = chunks.get(chunks.size()-1);
                    ceProgressMonitor.setProgress(val);
                }

                @Override
                protected void done()   {
                    ceProgressMonitor.close();
                    populateTable();
                }
                
            };
            cellExtractor.execute();
    }//GEN-LAST:event_performKnnClassificationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Initialization.setup();
                Dashboard db = new Dashboard();
//                db.setLayout(new BorderLayout());
//                JPanel statusPanel = new JPanel();
//                statusPanel.setBorder(new BevelBorder(BevelBorder.LOWERED));
//                db.add(statusPanel, BorderLayout.SOUTH);
//                statusPanel.setPreferredSize(new Dimension(db.getWidth(), 25));
//                statusPanel.setLayout(new BoxLayout(statusPanel, BoxLayout.X_AXIS));
//                JLabel statusLabel = new JLabel("status");
//                statusLabel.setHorizontalAlignment(SwingConstants.LEFT);
//                statusPanel.add(statusLabel);
                ((DefaultTableCellRenderer) cellTable.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);
                db.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseImageKnn;
    private javax.swing.JButton browseImageRF;
    private static javax.swing.JTable cellTable;
    private javax.swing.JMenuItem exitSystem;
    private javax.swing.JLabel imageContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField knnImagePath;
    private javax.swing.JMenuItem newFeatureFile;
    public static javax.swing.JSpinner numAttributes;
    public static javax.swing.JSpinner numNeighbours;
    public static javax.swing.JSpinner numTrees;
    private javax.swing.JMenuItem performAnalysis;
    private javax.swing.JButton performKnnClassification;
    private javax.swing.JButton performRFClassification;
    private javax.swing.JTextField rfImagePath;
    private javax.swing.JButton setNeightbours;
    private javax.swing.JMenuItem settings;
    private javax.swing.JButton trainRFClassifier;
    // End of variables declaration//GEN-END:variables
}
