/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Hp
 */
public class SettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        trainPath = new javax.swing.JTextField();
        testPath = new javax.swing.JTextField();
        rfClassificationFilePath = new javax.swing.JTextField();
        trainDataBrowse = new javax.swing.JButton();
        testDataBrowse = new javax.swing.JButton();
        rfFileBrowse = new javax.swing.JButton();

        jLabel1.setText("Training Data File Path");

        jLabel2.setText("Test Data File Path");

        jLabel3.setText("Random Forest Classification File Path");

        trainDataBrowse.setText("Browse");
        trainDataBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainDataBrowseActionPerformed(evt);
            }
        });

        testDataBrowse.setText("Browse");
        testDataBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testDataBrowseActionPerformed(evt);
            }
        });

        rfFileBrowse.setText("Browse");
        rfFileBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfFileBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trainPath)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(testPath)
                    .addComponent(rfClassificationFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testDataBrowse, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rfFileBrowse)
                        .addComponent(trainDataBrowse)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainDataBrowse))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testDataBrowse))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rfClassificationFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfFileBrowse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void trainDataBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainDataBrowseActionPerformed
        JFileChooser fc = new JFileChooser(Initialization.trainDataPath);
        fc.setDialogTitle("Select File");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text", "txt", "dat");
        fc.setFileFilter(filter);
        fc.removeChoosableFileFilter(fc.getAcceptAllFileFilter());
        int i = fc.showOpenDialog(this);
        if(i==JFileChooser.APPROVE_OPTION){
            try{
                trainPath.setText(fc.getSelectedFile().getPath());
            }
            catch(Exception e)  {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_trainDataBrowseActionPerformed

    private void testDataBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testDataBrowseActionPerformed
        JFileChooser fc = new JFileChooser(Initialization.testDataPath);
        fc.setDialogTitle("Select File");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text", "txt", "dat");
        fc.setFileFilter(filter);
        fc.removeChoosableFileFilter(fc.getAcceptAllFileFilter());
        int i = fc.showOpenDialog(this);
        if(i==JFileChooser.APPROVE_OPTION){
            try{
                testPath.setText(fc.getSelectedFile().getPath());
            }
            catch(Exception e)  {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_testDataBrowseActionPerformed

    private void rfFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfFileBrowseActionPerformed
        JFileChooser fc = new JFileChooser(Initialization.rfClassificationFilePath);
        fc.setDialogTitle("Select File");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text", "txt", "dat");
        fc.setFileFilter(filter);
        fc.removeChoosableFileFilter(fc.getAcceptAllFileFilter());
        int i = fc.showOpenDialog(this);
        if(i==JFileChooser.APPROVE_OPTION){
            try{
                rfClassificationFilePath.setText(fc.getSelectedFile().getPath());
            }
            catch(Exception e)  {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_rfFileBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField rfClassificationFilePath;
    private javax.swing.JButton rfFileBrowse;
    private javax.swing.JButton testDataBrowse;
    public static javax.swing.JTextField testPath;
    private javax.swing.JButton trainDataBrowse;
    public static javax.swing.JTextField trainPath;
    // End of variables declaration//GEN-END:variables
}
